server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.41.4:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}  # 동적으로 주입받음

spring :
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  kafka:
    kafka-server: kafka:9092
#  zipkin:
#    base-url: http://zipkin:9411
#    enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    redis:
      host: sj-cache-server.wlcmxa.ng.0001.apn2.cache.amazonaws.com
      port: 6379
  jpa:
    database: mysql
    #    InnoDB??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, busrefresh, refresh, loggers, env
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
#  zipkin:
#    tracing:
#      endpoint: "http://zipkin:9411/api/v2/spans"

file:
  dir: /Users/song/Desktop/study/SPRING-PROJECT/image-file/

logging:
  level:
    org.springframework.cache: trace
